<a href="https://colab.research.google.com/github/mmmerlyd/InteligenciaArtificial/blob/main/01JULIO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as algebraLineal

a=algebraLineal.array([11,22,33])
print(a.shape)
print(type(a))
print(a)


print(a[:2])
print(a[1:3])

a[1]=888
print(a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
[11 22]
[22 33]
[ 11 888  33]


In [32]:
import numpy as np
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)

print(b[1,1])
aux=b[1:,1:].copy()
print(aux.shape)
print(aux)

print('BEFORE/.....')
print(b)
print(aux)

aux[1,1]=100

print('AFTER/.....')
print(b)
print(aux)


(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
[[ 22  33]
 [222 333]]
BEFORE/.....
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 333]]
AFTER/.....
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[ 22  33]
 [222 100]]


In [21]:
#matriz
c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [22]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
g=np.random.random((5,5))
print(g)

[[0.52173469 0.67659198 0.6611671  0.14754743 0.42346961]
 [0.90927509 0.11706456 0.60641705 0.88828367 0.24939904]
 [0.79478953 0.18409012 0.45043259 0.25711101 0.48445872]
 [0.71001238 0.4362511  0.76788496 0.50573152 0.56646825]
 [0.27681569 0.55944509 0.7663124  0.24113223 0.54826285]]


In [35]:
tmp1=np.random.randint(1,20,(4,3))
print(tmp1)
rows=np.array([0,1,2,0])
cols=np.arange(4)
print(rows)
print(cols)
print(rows.shape)
print(cols.shape)


[[14  1  4]
 [15  7 13]
 [ 8 10 12]
 [ 6 12 12]]
[0 1 2 0]
[0 1 2 3]
(4,)
(4,)


In [45]:
tmp1[rows,cols]=100
print(tmp1)


[[100  28  23 100  30  20]
 [ 27 100  31  36  49  28]
 [ 42  37 100  41  22  20]
 [ 44  46  33  40  37  46]
 [ 43  41  45  29  48  25]
 [ 39  37  41  22  30  43]]


In [44]:
tmp1=np.random.randint(20,50,(6,6))
print(tmp1)

[[37 28 23 45 30 20]
 [27 25 31 36 49 28]
 [42 37 31 41 22 20]
 [44 46 33 40 37 46]
 [43 41 45 29 48 25]
 [39 37 41 22 30 43]]


In [52]:
filter=(tmp1>45)
print(filter)
print(tmp1[filter])

[[False False False False  True  True  True False  True False]
 [ True  True False  True  True  True False False  True False]
 [ True  True  True False False False  True False False False]
 [False  True  True  True  True False False False False False]
 [False  True False  True False False  True  True  True False]
 [False  True  True False False  True False  True  True False]
 [False  True False  True  True False  True  True  True  True]
 [ True False  True False False  True False  True  True False]
 [ True  True False False False False False False  True  True]
 [ True False  True False  True False  True  True  True False]]
[85 98 74 94 62 70 52 70 71 87 94 82 83 99 55 96 63 47 79 83 70 70 49 68
 76 85 96 76 92 70 51 67 59 60 70 90 90 68 82 58 81 53 56 74 87 96 73 76
 48 87]


In [51]:
tmp1=np.random.randint(1,100,(10,10))
print(tmp1)

[[30 35  1 18 85 98 74 35 94 18]
 [62 70 18 52 70 71 34 36 87 15]
 [94 82 83 13  7 14 99 38 44 20]
 [20 55 96 63 47  4 23 32 43 38]
 [38 79  5 83 39 16 70 70 49 15]
 [20 68 76 28 37 85 16 96 76 42]
 [ 1 92  2 70 51  2 67 59 60 70]
 [90  5 90 41 22 68 21 82 58 30]
 [81 53 13 27 34 14 34 15 56 74]
 [87 38 96  1 73 28 76 48 87 42]]


In [53]:
filter=(tmp1%2==0)
print(filter)
print(tmp1[filter])

[[ True False False  True False  True  True False  True  True]
 [ True  True  True  True  True False  True  True False False]
 [ True  True False False False  True False  True  True  True]
 [ True False  True False False  True False  True False  True]
 [ True False False False False  True  True  True False False]
 [ True  True  True  True False False  True  True  True  True]
 [False  True  True  True False  True False False  True  True]
 [ True False  True False  True  True False  True  True  True]
 [False False False False  True  True  True False  True  True]
 [False  True  True False False  True  True  True False  True]]
[30 18 98 74 94 18 62 70 18 52 70 34 36 94 82 14 38 44 20 20 96  4 32 38
 38 16 70 70 20 68 76 28 16 96 76 42 92  2 70  2 60 70 90 90 22 68 82 58
 30 34 14 34 56 74 38 96 28 76 48 42]


In [55]:
tmp3=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp3.dtype)

float64


In [61]:
x=np.array([[1,2],[11,22]])
y=np.array([[22,33],[44,55]])
print(x)
print(y)

print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))

[[ 1  2]
 [11 22]]
[[22 33]
 [44 55]]
[[23 35]
 [55 77]]
[[-21 -31]
 [-33 -33]]
[[  22   66]
 [ 484 1210]]
[[0.04545455 0.06060606]
 [0.25       0.4       ]]
[[1.         1.41421356]
 [3.31662479 4.69041576]]


In [63]:
tmp1=np.random.randint(1,10,(2,5))
print(tmp1)
aux=tmp1.mean()
print(aux)

[[1 9 1 1 6]
 [6 3 8 2 5]]
4.2


In [65]:
print(tmp1.mean(axis=1))
print(tmp1.mean(axis=0))

[3.6 4.8]
[3.5 6.  4.5 1.5 5.5]
