<a href="https://colab.research.google.com/github/mmmerlyd/InteligenciaArtificial/blob/main/ACTIVIDADPYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Dominguez Zambrano Merly Mishelle

In [3]:
#Ejercicio 1
# Importa numpy como np y mira la versión
import numpy as np
print(np.__version__)

1.25.2


In [5]:
#Ejercicio 2
#Crea una matriz de 10  números del 0 al 9
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Ejercicio 3
#Crea un vector aleatorio de tamaño 10 y reemplaza el valor máximo por 0
import numpy as np
b=np.random.rand(10)
indice_maximo = np.argmax(b)
b[indice_maximo] = 0
print(b)

[0.35979253 0.7797502  0.66988761 0.         0.27464067 0.26492893
 0.00491528 0.55346973 0.26397866 0.68371903]


In [12]:
#Ejercicio 4
# Imprima el número 8 de la siguiente matriz
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,2])


8


In [14]:
#Ejercicio 5
#Imprima los números [3, 4, 5] de la siguiente matriz
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])

[3 4 5]


In [16]:
#Ejercicio 6
# Imprima los últimos 4 números de la siguiente matriz
arr = np.array([1,2,3,4,5,6,7])
print(arr[-4:])

[4 5 6 7]


In [19]:
#Ejercicio 7
# Crea una matriz numpy de 3×3 de todos los valores True
import numpy as np
arr=np.full((3, 3), True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [20]:
#Ejercicio 8
# Extraer todos los números impares de arr
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr%2==1])

[1 3 5 7 9]


In [2]:
#Ejercicio 9
# Crea un vector con valores que van desde 10 hasta 49
import numpy as np
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#Ejercicio 10
#Invertir un vector (el primer elemento se convierte en el último)
arr=np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [4]:
#Ejercicio 11
# Cree una matriz de 10x10 con valores enteros aleatorios y encuentre los valores mínimo y máximo
import numpy as np
matriz = np.random.randint(0, 100, size=(10, 10))
valor_minimo = np.min(matriz)
valor_maximo = np.max(matriz)
print("Matriz:\n", matriz)
print("\nValor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)

Matriz:
 [[38 61 53 69 87 46  5 65 77 75]
 [90 76 70 66 79  7 36 90 37 74]
 [24 20 58 27 22 64 15 68 47 57]
 [79 81  1 39 96 82 83 97 75  8]
 [45 73 51 95 12  5 48 83 76 87]
 [85 49 90 31 96 78 99 47 93 98]
 [43 86 70 90 33  2 13 53 91  4]
 [87 32 54 49  9 34 71 24  0 54]
 [84 60 75 76 54 86 24 23 40 27]
 [10 93 39 83  1 70 52 81 71  6]]

Valor mínimo: 0
Valor máximo: 99


In [5]:
#Ejercicio 12
# Crea una matriz de 3x3x3 con valores aleatorios
import numpy as np
matriz = np.random.rand(3, 3, 3)
print(matriz)


[[[0.56018254 0.9157011  0.13478301]
  [0.25968634 0.90318447 0.8907412 ]
  [0.67566622 0.44256517 0.39893443]]

 [[0.97689811 0.58241315 0.34067282]
  [0.01742389 0.84768877 0.51297548]
  [0.67543808 0.05159536 0.42381073]]

 [[0.27422634 0.42972504 0.79382778]
  [0.9448887  0.28958845 0.97287651]
  [0.4406626  0.15954419 0.48635518]]]


In [7]:
#Ejercicio 13
#Reemplace todos los números impares en arr con -1
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[arr%2==0]=-1
print(arr)

[ 1 -1  3 -1  5 -1  7 -1  9]


In [12]:
#Ejercicio 14
#Crear una matriz de tipo float
import numpy as np
arr= np.array([[1.2, 3.5, 5.1],
                         [7.2, 9.9, 2.8]], dtype=np.float64)
print(arr)
print("Tipo de dato de la matriz:", arr.dtype)


[[1.2 3.5 5.1]
 [7.2 9.9 2.8]]
Tipo de dato de la matriz: float64


In [2]:
#Ejercicio 15
#Convertir una matriz 10 en una matriz 20 con 2 filas
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr=np.reshape(arr,(2,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
#Ejercicio 16
#¿Cómo encontrar valores comunes entre dos matrices?
#Z1 = np.random.randint(0,10,10)
#Z2 = np.random.randint(0,10,10)
import numpy as np
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
valores_comunes = np.intersect1d(Z1, Z2)
print("Matriz Z1:", Z1)
print("Matriz Z2:", Z2)
print("Valores comunes:", valores_comunes)

Matriz Z1: [1 3 1 2 2 5 2 4 2 3]
Matriz Z2: [8 7 8 1 1 7 5 5 6 5]
Valores comunes: [1 5]


In [4]:
#Ejercicio 17
#Considere dos matrices aleatorias A y B, verifique si son iguales
# A = np.random.randint(0,2,5)
# B = np.random.randint(0,2,5)
import numpy as np
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
son_iguales = np.array_equal(A, B)
print("Matriz A:", A)

Matriz A: [0 1 0 0 1]


In [5]:
#Ejercicio 18
#Apilar las matrices a y b verticalmente
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


In [6]:
#Ejercicio 19
#Apile las matrices a y b horizontalmente.
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b))
print(c)

[1 2 3 4 5 6]


In [9]:
#Ejercicio 20
#Obtener todos los elementos entre 5 y 10 de la matriz tmp
import numpy as np
tmp = np.arange(15)
arr = tmp[(tmp >= 5) & (tmp <= 10)]
print(arr)

[ 5  6  7  8  9 10]
